name: Construcción y despliegue de Systm_Web en Azure App Service

env:
  AZURE_WEBAPP_NAME: upt-aspnet-app  # Nombre de la aplicación en Azure
  AZURE_WEBAPP_PACKAGE_PATH: '.'     # Ruta al paquete compilado
  BUILD_CONFIGURATION: 'Release'     # Configuración de compilación

on:
  push:
    branches: [ "main" ]  # Se activa al hacer push a la rama main
  workflow_dispatch:      # Permite ejecutar manualmente

jobs:
  build:
    runs-on: windows-latest  # Usa un entorno Windows para .NET Framework
    steps:
      # Paso 1: Checkout del repositorio
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |  # Configuración de sparse-checkout
            /*
            !**/aspnet_client  # Excluye la carpeta aspnet_client
            !**/packages       # Excluye la carpeta packages
          cone: false          # Desactiva el modo "cone" para permitir exclusiones
      
      # Paso 2: Configurar Git para rutas largas
      - name: Configurar Git para rutas largas
        run: git config --global core.longpaths true

      # Paso 3: Configurar MSBuild
      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v1

      # Paso 4: Restaurar paquetes NuGet
      - name: Restaurar paquetes NuGet
        working-directory: Systm_Web
        run: nuget restore Systm_Web.sln

      # Paso 5: Compilar la aplicación con MSBuild
      - name: Compilar la app con MSBuild
        working-directory: Systm_Web
        run: msbuild Systm_Web.sln /p:Configuration=${{ env.BUILD_CONFIGURATION }}

      # Paso 6: Crear el paquete de despliegue
      - name: Crear el paquete de despliegue
        working-directory: Systm_Web
        run: Compress-Archive -Path "./bin/${{ env.BUILD_CONFIGURATION }}/net48/*" -DestinationPath "../Systm_Web-package.zip"

      # Paso 7: Subir el paquete como artefacto
      - name: Subir el paquete como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Systm_Web-package
          path: Systm_Web-package.zip

  deploy:
    needs: build  # Depende del job "build"
    runs-on: windows-latest
    permissions:
      contents: none
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      # Paso 1: Descargar el paquete de la app
      - name: Descargar el paquete de la app
        uses: actions/download-artifact@v4
        with:
          name: Systm_Web-package

      # Paso 2: Desplegar a Azure App Service
      - name: Desplegar a Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: Systm_Web-package.zip