name: Construcción y despliegue de Systm_Web en Azure App Service

env:
  AZURE_WEBAPP_NAME: upt-aspnet-app  # Nombre de la aplicación en Azure
  BUILD_CONFIGURATION: 'Release'     # Configuración de compilación

on:
  push:
    branches: [ "main" ]  # Se activa al hacer push a la rama main
  workflow_dispatch:      # Permite ejecución manual

jobs:
  build:
    runs-on: windows-latest  # Usa un entorno Windows para .NET Framework
    steps:
      # Paso 1: Checkout del repositorio
      - uses: actions/checkout@v4

      # Paso 2: Configurar MSBuild
      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v1

      # Paso 3: Restaurar paquetes NuGet
      - name: Restaurar paquetes NuGet
        working-directory: Systm_Web
        run: nuget restore Systm_Web.sln

      # Paso 4: Compilar la aplicación con MSBuild
      - name: Compilar la app con MSBuild
        working-directory: Systm_Web
        run: msbuild Systm_Web.sln /p:Configuration=${{ env.BUILD_CONFIGURATION }}

      # Paso 5: Verificar la carpeta de salida y su contenido
      - name: Verificar carpeta de salida
        working-directory: Systm_Web
        run: |
          # Verificar si la carpeta bin/Release existe
          if (Test-Path -Path "./bin/Release") {
              Write-Output "La carpeta bin/Release existe."
              Get-ChildItem -Path "./bin/Release" -Recurse
          } else {
              Write-Error "La carpeta bin/Release no existe."
              exit 1
          }

      # Paso 6: Crear el paquete de despliegue
      - name: Crear el paquete de despliegue
        working-directory: Systm_Web
        run: |
          # Comprimir los archivos de la carpeta bin/Release/
          Compress-Archive -Path "./bin/Release/*" -DestinationPath "../Systm_Web-package.zip"

      # Paso 7: Subir el paquete como artefacto
      - name: Subir el paquete como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Systm_Web-package
          path: Systm_Web-package.zip

  deploy:
    needs: build  # Depende del job "build"
    runs-on: windows-latest
    permissions:
      contents: none
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      # Paso 1: Descargar el paquete de la app
      - name: Descargar el paquete de la app
        uses: actions/download-artifact@v4
        with:
          name: Systm_Web-package

      # Paso 2: Desplegar a Azure App Service
      - name: Desplegar a Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: Systm_Web-package.zip
